vectorgrp/sil-kit

.github/actions/build-cmake-preset/action.yml, .github/workflows/build-linux-asan.yml, .github/workflows/build-linux-ci.yml, .github/workflows/build-linux-featurebranch.yml, .github/workflows/build-linux-main.yml, .github/workflows/build-linux-tsan.yml, .github/workflows/build-linux-ubsan.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-win-main.yml, .github/workflows/build-windows-ci.yml, .github/workflows/build-windows-featurebranch.yml, .gitignore, CMakePresets.json
Run CI for Pull Requests and feature branch on this repo
Store Artifacts if necessary
Precursor for doing CR Runs in the SIL KIT repo
Check if the CI runs without errors
=> SILKIT-1510: Enable CI on github.com

.github/workflows/build-linux.yml
and remove the packaging of artifacts
=> -- ci: fix workflow job name

.github/workflows/build-linux-asan.yml, .github/workflows/build-linux-tsan.yml, .github/workflows/build-linux-ubsan.yml, .github/workflows/build-linux.yml, .github/workflows/build-win.yml
=> SILKIT-1510 ci: stop workflow on new pushes

README.rst
The RST rendering in github changed. This restores the previous horizontal alignment
=> -- readme: fix badge formatting

SilKit/IntegrationTests/ITest_Abort.cpp
The subtest test_Abort_Stopped_Simulation_Sync in ITest_Abort is flakey and possibly fails (locally reproducible on clang-release builds after several iterations).
The test had wrong expectations for the emerging ParticipantStates:
In the test, the system controller stops the simulation and aborts in the stop handler.
However it can happen that a participant is done with the stop before the abort arrives.
This is fixed by extending the expectations for the participants states that can emerge on a valid path from stop->shutdown.
=> Fix flakey ITest_Abort

SilKit/cmake/SilKitVersion.cmake, docs/CHANGELOG.rst
=> -- release: update changelog and bump version to 4.0.48

SilKit/ci/Jenkinsfile
=> -- ci: use main-mirror for jenkinsfile

.github/workflows/build-release-packages.yml
Moved the docker image from docker hub to github container registry. The repository with the docker file and docker build action may be moved in the future.
=> -- ci: update docker image used in release workflow

.github/workflows/build-linux.yml, .github/workflows/build-release-packages.yml
Forgot to change the new docker image in two workflows.
This will fix the PR builds on Linux.
=> -- ci: change remaining docker images to new one

.github/workflows/linux-asan.yml, .github/workflows/linux-tsan.yml, .github/workflows/linux-ubsan.yml, .github/workflows/sil-kit-ci.yml, README.rst
[WIP] check the reintroduction of our Linux sanitizer workflows
=> Reintroduce linux sanitizer workflows for badges

SilKit/cmake/SilKitVersion.cmake, docs/CHANGELOG.rst
=> -- release: update changelog and bump version to 4.0.49

CMakeLists.txt
Fix Linux packaging. The linker map file is missing
=> SILKIT-1543: cmake: fix packaging on Linux

SilKit/cmake/SilKitVersion.cmake, docs/CHANGELOG.rst
=> -- release: update changelog and bump version to 4.0.50

.github/workflows/build-win.yml
Check if win-2019 fixes the build
=> ci: change to windows-2019 due to missing toolset

.github/workflows/build-win.yml, .github/workflows/linux-asan.yml, .github/workflows/linux-tsan.yml, .github/workflows/linux-ubsan.yml, .github/workflows/sil-kit-ci.yml
Fix the badges for our main branch builds
No ticket available, just a hot fix!
=> workflows: fix badges for sanitizer + win builds

README.rst, SilKit/source/CMakeLists.txt
Small fixes to clean up the backlog
Issues:
SILKIT-1560
SILKIT-929
=> Fix README and CMakeLists log messages

Demos/Ethernet/EthernetDemo.cpp
Remove unused SILKIT_HOURGLASS #ifdef
=> -- demos: remove unused #ifdef

.github/workflows/sil-kit-ci.yml, SilKit/ci/check_formatting.py
Add a workflow to check for correct clang-format source code formatting!
=> ci: add check formatting workflow

SilKit/source/config/ParticipantConfigurationFromXImpl.cpp, SilKit/source/config/YamlConversion.cpp
Fixes a bug in the parsing code for the experimental section.
=> config: fix parsing of experimental section

SilKit/source/core/internal/TestDataTraits.hpp, SilKit/source/core/internal/traits/SilKitMsgTraits.hpp
The traits were "formatted" extremely unreadable, due to the semicolons being included in the macro.
=> maintenance: fix formatting of SilKitMsgTraits.hpp

SilKit/source/config/ParticipantConfigurationFromXImpl.cpp
=> fixup: Use right node in cache population

SilKit/CMakeLists.txt, SilKit/IntegrationTests/CMakeLists.txt, SilKit/IntegrationTests/Hourglass/CMakeLists.txt, SilKit/IntegrationTests/ITest_NetSim.hpp, SilKit/cmake/SilKitTest.cmake, SilKit/cmake/SilKitTest/SilKitTestMain.cpp, Utilities/SilKitRegistry/config/CMakeLists.txt
Cleanup integration test definitions and split off separate executable for integration tests (and function tests) using internals.
=> cmake: add separate executable for integration tests using internals

Utilities/SilKitRegistry/config/CMakeLists.txt
Fix CMake such that SIL Kit can be build with tests disabled.
=> cmake: check if test target exists before adding compile definitions

Demos/Benchmark/BenchmarkDemo.cpp
=> maintenance: in benchmark demo, let registry choose a free port

.github/workflows/build-macos.yml, .github/workflows/sil-kit-ci.yml, SilKit/source/extensions/Tests/Test_SilKitExtensions.cpp, SilKit/source/util/ExecutionEnvironment.cpp, SilKit/source/util/SetThreadName.cpp, SilKit/source/util/SignalHandler.cpp
Ensure that the utilties build on *BSD and macOs
=> util: fix build on macOs and *BSD

SilKit/cmake/SilKitVersion.cmake, docs/CHANGELOG.rst
Bump version after latest release
=> bump version to 4.0.54

docs/CHANGELOG.rst
=> Update release date in CHANGELOG.rst

Demos/communication/Lin/LinSlaveDemo.cpp
=> demos: fix warning in LinSlaveDemo

Demos/CMakeLists.txt, docs/CHANGELOG.rst
=> demos: set rpath for installed demos

SilKit/include/silkit/detail/impl/services/orchestration/LifecycleService.hpp
=> hourglass: cleaner final state future

docs/CHANGELOG.rst
=> docs: reword and update changelog

Demos/tools/Benchmark/BenchmarkDemo.cpp, docs/demos/tool.rst
- Aligned optional and positional command line arguments.
- Docs update (simulation step size, service type as command line arguments).
=> fix docs for benchmark demo

docs/CHANGELOG.rst
Final changelog update (added the QA notice and the missing `Changed` subsection header).
=> docs: update changelog

SilKit/cmake/SilKitVersion.cmake, docs/CHANGELOG.rst
Bump the version from 4.0.55 to 4.0.56 and add the changelog entry.
=> version: bump to 4.0.56

SilKit/source/dashboard/Service/SilKitEventHandler.cpp, SilKit/source/services/logging/Logger.cpp, SilKit/source/util/StringHelpers.cpp, SilKit/source/util/Uri.cpp
Update and fix build issues
- asio 1.30.2
- fmt 11.1.4
- spdlog 1.15.2
=> SILKIT-1740 Update third parties to latest stable releases

SilKit/source/config/ParticipantConfiguration.cpp, SilKit/source/dashboard/CMakeLists.txt, SilKit/source/services/orchestration/TimeSyncService.cpp
Fixes a few issues with modern clangs.
=> ci: fix warnings on modern clang

Demos/communication/Can/CanDemoCommon.hpp, SilKit/IntegrationTests/FTest_CanWithoutSync.cpp, SilKit/IntegrationTests/ITest_CanDemo.cpp, SilKit/include/silkit/capi/Can.h, SilKit/include/silkit/services/can/ICanController.hpp, SilKit/source/services/can/Test_CanSerdes.cpp, docs/api/services/can.rst, docs/overview/overview.rst
Clarify that we support CAN XL. Update some tests and the Demo to print XL frames if received.
Also CAN XL supports up to 20mbit/s
=> SILKIT-1743 can xl: update docs, tests and demo

docs/CHANGELOG.rst
We forgot to fix the Changelog date for the last RC
=> update changelog for 2025 QA2 release

SilKit/IntegrationTests/ITest_Config.cpp
=> tests: fix integer-comparison warning

SilKit/source/core/vasio/PeerMetrics.cpp, SilKit/source/core/vasio/PeerMetrics.hpp, SilKit/source/services/orchestration/TimeSyncService.cpp
add explicit types in the metric names, and change from counter (ever increasing) to statistics.
also add bandwidth metrics.
SILKIT-1799
=> dashboard: anotate types to metric names

SilKit/cmake/SilKitVersion.cmake, docs/changelog/overview.rst, docs/changelog/versions/5.0.0.md, docs/changelog/versions/latest.md
Bump the version from 5.0.0 to 5.0.1 and add the changelog entry.
=> version: bump to 5.0.1

SilKit/source/config/ParticipantConfiguration.hpp, SilKit/source/config/ParticipantConfigurationFromXImpl.cpp, SilKit/source/config/YamlReader.cpp, SilKit/source/config/YamlWriter.cpp, SilKit/source/core/participant/Participant_impl.hpp, SilKit/source/core/vasio/VAsioRegistry.cpp, Utilities/SilKitRegistry/Registry.cpp, Utilities/SilKitRegistry/config/RegistryConfiguration.cpp, docs/configuration/configuration.rst, docs/configuration/experimental-configuration.rst, docs/troubleshooting/advanced.rst, docs/troubleshooting/troubleshooting.rst, docs/utilities/utilities.rst
Document the `Experimental: Metrics` config options and mention the Dashboard.
=> docs: add experimental metrics and SIL Kit Dashboard
