SilKit/source/CMakeLists.txt
SilKit/source/silkit.map

Adds a version script to the linkage of the main SIL Kit library which only makes
- the C symbols (i.e., `SilKit_*`)
- and the 'legacy' C++ symbols (all functions defined in `SilKit/source/LegacyAbi.cpp`)
visible in the `.so`.
This works for both, the Release and Debug builds.
The resulting library was tested with the demos from this repository, the adapters, and the simulator.

-- linux: add and use linker version script

---

SilKit/IntegrationTests/ITest_Dashboard.cpp

The netsim_coordinated test would immediately call the stop function of the simulation participant which would result in the dashboard 'seeing' the stop state before the running state and the test would fail.
This delays the Stop() until at least on step duration has passed (1 step) which fixes the issue of dashboard missing states.
>

ITest_Dashboard: delay Stop() in SimStepHandler

---

SilKit/cmake/SilKitTest.cmake

Due to the test consolidation, the individual test executables are added as tests in a different place in the CMake scripts. A piece of CMake script hidden behind an if caused the configuration step to fail for builds on MinGW. This PR removes this piece of code. Testing seems to work (at least for me) without the removed code.

-- cmake on mingw: remove broken and obsolete code

---

SilKit/source/capi/CapiParticipant.cpp

In the C-API `SilKit_ParticipantConfigurationFromFile` implementation for `_WIN32` platforms we use a non-standard overload of the `std::ifstream` constructor which takes a `std::wstring` (to allow unicode symbols in the path). This PR switches to the overload taking a `const wchar_t *` which is provided on MSVC as well as MinGW.

-- mingw: use ifstream constructor taking a const wchar_t *

---

CMakeLists.txt

Use `-Wa,-mbig-obj` to allow bigger object files generated by the assembler. This solved an issue that occured during testing of the MinGW builds.

-- cmake on mingw: use big-obj with gcc and clang

---

SilKit/source/config/Configuration.hpp
SilKit/source/util/FileHelpers.cpp

Windows build + tests were broken due to
* Wrong comparison operator
* Suboptimal platform detection in FileHelpers.cpp
No ticket available

Fix win builds

---

SilKit/source/util/SignalHandler.cpp

The `sil-kit-system-controller` currently crashes (SEGFAULT) if the simulation is stopped externally. This happens because the handler is called when the `SignalMonitor` instance is destroyed, and the handler calls the logging functions on a destroyed object.
The fix checks that the signal number is not the 'default' / 'invalid' signal number before calling the handler.
Please run the system controller and a participant that can be stopped 'by hand' without exiting the process. Then, when the participant stops, the system controller should exit normally. Check the exit code (PowerShell: `$LASTEXITCODE`, shell: `$?`).

-- utilities: signal monitor: do not call signal handler upon destruction

---

.github/workflows/build-linux.yml
.github/workflows/build-win.yml
.github/workflows/linux-asan.yml
.github/workflows/linux-tsan.yml
.github/workflows/linux-ubsan.yml
.github/workflows/sil-kit-ci.yml
SilKit/ci/check_files_changed.py

We do not need to run the CI if we want to change the CHANGELOG or the README file. This is done mostly for the release process, where we want to make sure that the CHANGELOG is up-to-date without waiting for the CI to finish!

-- ci: remove builds in CI for metadata changes

---

SilKit/source/extensions/SilKitExtensionApi/SilKitExtensionUtils.hpp

The clang builds relied on __GNUC__ to be set for extension loading. Rather use __clang__major instead.
We need to rework the extension loading constraints in the future anyway

-- extensions: don't rely on __GNUC__ in clang builds

---

.editorconfig

This fixes that Visual Studio ignores the indent settings in the .clang-format file.

-- add editorconfig

---

.github/workflows/build-win.yml

For the build-win workflow, the build-arch: x86 was missing for the win32 job. This parameter is passed to https://github.com/ilammy/msvc-dev-cmd to set up the developer console.

-- ci: Pass x86 to build action for win32 builds

---

.github/workflows/sil-kit-ci.yml

~~DONT MERGE: DEPENDS ON https://github.com/vectorgrp/sil-kit/pull/39~~
UPDATE: Rebased on main instead of PR #39 . Can be merged now
Push CI was broken due to mismatched and missing filters in the CI yml for the workflows. This fixes the issue with hopefully minimal effort.
Checked here, albeit with a minor change to use the feature branch as the `on: push` filter. Unfortunately in this PR we can only test it after we merged it.

Fix push ci 

---

.github/workflows/build-linux.yml

The Ubuntu 18.04 doesn't work well with the current upload-artifact action. Upgrade to 22.04 for now, until we refactor our builds to only run the CMake step in the target container.

-- ci: build linux releases with GCC on Ubuntu 22.04

---

.github/workflows/build-linux.yml
CMakePresets.json

the linux-release cmake preset uses a legacy build directory which doesnt work with our CI workflows.

-- ci: use gcc-release preset for builds

---

SilKit/source/config/Configuration.hpp
SilKit/source/config/ParticipantConfigurationFromXImpl.cpp
SilKit/source/config/TestParticipantConfigs/ParticipantConfiguration_FullIncludes.yaml
SilKit/source/config/TestParticipantConfigs/ParticipantConfiguration_FullIncludes_Reference.yaml
SilKit/source/config/Test_ParticipantConfiguration.cpp

The current implementation had a bug, which prohibited a user from adding a remote and a stdout sink at the same time to a participant. The bug was fixed by adding separate caches for each logging sink type.
Build the CanDemo. Run the CanDemo with the folloging logging Config:
> Logging:
Sinks:
- Type: Remote
Level: Trace
LogName: CanWriterLog
- Type: Stdout
Level: Trace
LogName: CanWriterLog

config: add separate cache for stdout/remote sinks

---

SilKit/source/dashboard/CMakeLists.txt
SilKit/source/dashboard/Client/DashboardSystemApiClient.hpp
SilKit/source/dashboard/Client/DashboardSystemServiceClient.cpp
SilKit/source/dashboard/Client/DashboardSystemServiceClient.hpp
SilKit/source/dashboard/Client/IDashboardSystemServiceClient.hpp
SilKit/source/dashboard/Client/Mocks/MockDashboardSystemServiceClient.hpp
SilKit/source/dashboard/DashboardBulkUpdate.cpp
SilKit/source/dashboard/DashboardBulkUpdate.hpp
SilKit/source/dashboard/DashboardInstance.cpp
SilKit/source/dashboard/DashboardInstance.hpp
SilKit/source/dashboard/Dto/BulkUpdateDto.hpp
SilKit/source/dashboard/Service/ISilKitEventHandler.hpp
SilKit/source/dashboard/Service/ISilKitToOatppMapper.hpp
SilKit/source/dashboard/Service/Mocks/MockSilKitEventHandler.hpp
SilKit/source/dashboard/Service/Mocks/MockSilKitToOatppMapper.hpp
SilKit/source/dashboard/Service/SilKitEventHandler.cpp
SilKit/source/dashboard/Service/SilKitEventHandler.hpp
SilKit/source/dashboard/Service/SilKitToOatppMapper.cpp
SilKit/source/dashboard/Service/SilKitToOatppMapper.hpp
SilKit/source/dashboard/Service/Test_DashboardSilKitEventHandler.cpp
SilKit/source/dashboard/Service/Test_DashboardSilKitToOatppMapper.cpp
docs/CHANGELOG.rst

These changes allow the dashboard client in SIL Kit to use the bulk-update endpoint (currently only available in a feature branch of the dashboard that is not publically available).
It allows for much larger simulations, as multiple changes can be combined into a single HTTP request.

SILKIT-1525: Use bulk-update endpoint of dashboard backend service

---

.editorconfig
SilKit/IntegrationTests/CMakeLists.txt
SilKit/IntegrationTests/FTest_WallClockCoupling.cpp
SilKit/IntegrationTests/ITest_Internals_ParticipantModes.cpp
SilKit/source/config/ParticipantConfiguration.hpp
SilKit/source/config/ParticipantConfiguration.schema.json
SilKit/source/config/ParticipantConfigurationFromXImpl.cpp
SilKit/source/config/ParticipantConfiguration_Full.json
SilKit/source/config/YamlConversion.cpp
SilKit/source/config/YamlConversion.hpp
SilKit/source/config/YamlSchema.cpp
SilKit/source/core/internal/IParticipantInternal.hpp
SilKit/source/core/mock/participant/MockParticipant.hpp
SilKit/source/core/participant/Participant.hpp
SilKit/source/core/participant/Participant_impl.hpp
SilKit/source/services/orchestration/LifecycleManagement.cpp
SilKit/source/services/orchestration/LifecycleManagement.hpp
SilKit/source/services/orchestration/LifecycleService.cpp
SilKit/source/services/orchestration/LifecycleStates.cpp
SilKit/source/services/orchestration/TimeSyncService.cpp
SilKit/source/services/orchestration/TimeSyncService.hpp
docs/CHANGELOG.rst
docs/configuration/configuration.rst
docs/configuration/experimental-configuration.rst

Introduce wall clock coupling of virtual time. Accessible via participant configuration: 
```
Experimental:
TimeSynchronization:
AnimationFactor: 1.0
```
- Added a _WallClockCoupling_ thread similar to the _WatchDog_ thread that manages the time advances when due
- Prevent sending NextSimTask at other places than the _WallClockCoupling_ thread  if the coupling is active
- Improved performance for mixed system w/ wo/ time synchronization by not sending NextSimTask message to participants that don't use a TimeSyncService:
- The timeSyncService is created by default with a lifecycle service, although it might be unused
- Now, controllers can be created internally without performing the message subscriptions (preventing `RegisterSilKitService`)
- For the TimeSyncService, the subscriptions are …

-- time sync: Couple virtual time to wall clock

---

SilKit/ci/check_files_changed.py

Version bumps should not trigger a CI build.\

ci: add SilKitVersion.cmake to exceptions

---

SilKit/ci/Jenkinsfile

This re-enables windows documentation builds. 
The windows jenkins nodes are now fixed at python 3.9, for running sphinx/ docs target

ci: fix docs build on jenkins

---

SilKit/ci/Jenkinsfile

Use python 3.9 on windows Jenkins runners.
Missed some python invocations in #82.

ci: really use python 3.9 on windows runners

---

SilKit/cmake/SilKitBuildSettings.cmake

-Wdangling-reference can produce false positives which break our builds. Therefor we disable it for now!

cmake: disable -Wdangling-reference for gcc > 13

---

CMakePresets.json
SilKit/source/services/metrics/MetricsManager.cpp
SilKit/source/services/metrics/MetricsManager.hpp

Fix sporadic unit test failures on MSVC RelWithDebInfo builds.
Turns out that the calls to `steady_clock::now()` return the same value sometimes (on Windows!). 
Those calls are now wrapped and checked against the previous value and it's ensured that the timestamp increases strictly monotonically.

tests: fix usage of steady_clock in MetricsManager on windows

---

SilKit/source/dashboard/DashboardInstance.cpp
docs/CHANGELOG.rst

Issue: SILKIT-1586
The `response` object is null if the server isn't available.
Run the registry with `--dashboard-uri` / `--enable-dashboard` but without running the dashboard itself (i.e., nothing to connect to).

dashboard: fix crash when dashboard is unavailable

---

SilKit/source/core/vasio/CMakeLists.txt
SilKit/source/core/vasio/RingBuffer.cpp
SilKit/source/core/vasio/RingBuffer.hpp
SilKit/source/core/vasio/Test_RingBuffer.cpp
SilKit/source/core/vasio/VAsioPeer.cpp
SilKit/source/core/vasio/VAsioPeer.hpp

Use a ring buffer for storing data from byte stream. 
This change is introduced for two reasons. First, the message buffer operations w.r.t. reading (e.g. write position) are encapsulated, which results in an improved code readability. Second, a smaller number of copies is necessary when an entire message is passed to the VAsioConnection.
Note that this change does not affect the performance (latency, throughput).
- Error handling for write/read: Currently, a boolean is returned (false, if the operation did not succeed). Hence, the class user is responsible for handling an unsuccessful write/read. Is that fine?
- Some member functions are currently unused, but have been useful for the development (write/read for single values, print function). Should those be deleted?
- Testing: Did I …

SILKIT-1571 core: add ring buffer for storing data from byte stream

---

SilKit/source/util/CMakeLists.txt

The `ExecutinEnvironment.cpp` compilation produces a warning regarding missing the `_WIN32_WINNT` definition. This should not happen anymore.

cmake: add _WIN32_WINNT define to I_SilKit_Util

---

SilKit/cmake/SilKitVersion.cmake
docs/CHANGELOG.rst

Halite is out and we need to update the version number at the beginning of the development cycle.

bump version to 4.0.53

---

.github/workflows/build-linux.yml
.github/workflows/build-release-packages.yml
.github/workflows/sil-kit-ci.yml

use the newly  created images from the dedicated sil-kit-docker-build repo for CI/CT purposes.

ci: update docker images

---

.github/workflows/build-linux-arm64.yml
.github/workflows/build-win.yml
.github/workflows/sil-kit-ci.yml

Make sure that we don't run the `sil-kit-ci` workflow and the individual `build-win` workflows on pushes to main.
Also remove the concurrency group from `build-win`, because it'll get canceled if CI runs in parallel.

ci: don`t run CI and workflows on push to main

---

Demos/Benchmark/BenchmarkDemo.cpp

Do not use port number used by autostarted registry (8500), but port number 8600 instead.

maintenance: fix registry port number used in benchmark demo

---

SilKit/include/silkit/util/serdes/Deserializer.hpp
SilKit/include/silkit/util/serdes/Serializer.hpp
SilKit/source/util/tests/Test_SilSerDes.cpp
docs/CHANGELOG.rst

This change allows to (de-)serialize unions using the public serdes headers. It does not change the API of the `Serializer` / `Deserializer` classes, but only implements the existing member functions.
The index is 1-based, since a related piece of software already uses 1-based indices for union discriminators.

api: serdes: allow union (de)serialization

---

.github/actions/build-cmake-preset/action.yml
.github/workflows/build-macos.yml
.github/workflows/build-mingw64.yml
.github/workflows/build-win.yml

Move the runner setup into the workflows and keep the build-cmake-preset
action as simple as possible.
Add workflow_dispatch to mingw so we can run it manually.

ci: clean up build workflows

---

SilKit/source/services/orchestration/TimeSyncService.cpp
SilKit/source/services/orchestration/TimeSyncService.hpp
docs/CHANGELOG.rst

- The Log message "Finished Simulation Step. Execution time was: ..." measures the SimStepHandler execution time. This is misleading when using the  `SimStepHandlerAsync`, because the simulation step is actually not finished.
- If using the `SimStepHandlerAsync`, the Log Message "Finished Simulation Step. Execution time was: ..." is now printed after the call to `CompleteSimulationStep`.
- The metric to time the SimStepHandler execution has been renamed to _SimStepHandlerExecutionDuration_
- If using the `SimStepHandlerAsync`,  the new metric _SimStepCompletionDuration_ measure the interval between the end of the handler and the call to `CompleteSimulationStep`.

dev: For SimStepAsync, measure execution time until call to CompleteSimStep

---

SilKit/source/core/internal/ServiceDescriptor.hpp
SilKit/source/experimental/netsim/SimulatedNetworkInternal.cpp
SilKit/source/experimental/netsim/SimulatedNetworkInternal.hpp
SilKit/source/experimental/netsim/SimulatedNetworkRouter.cpp
SilKit/source/experimental/netsim/SimulatedNetworkRouter.hpp
docs/CHANGELOG.rst

Using Trace Logging in the NetSim API caused the exception `supplementalData.size() > 0`
This was the case because the controllerType (by name) was not saved on the supplemental data of the mirrored controller in the NetSim API when a new controller got discovered. 
With log level Trace, the mirrored controller then caused the exeption when trying to log the controller type in its service descriptor.
Finally, the exception got catched in the hourglass `CAPI_CATCH_EXCEPTIONS`.
Fixed by writing the controller type in the suppl. info map of the mirrored controller. Also made the exception more specific.
- Code Review
- Build this branch, make sure the NetSim uses the SilKit.dll with the fix.
- Run a Demo with NetSim and  `-l trace` on the Netsim.exe (or via trace lvl in the participant …

dev: Add missing controllerType in ServiceDescriptor of SimulatedController

---

SilKit/source/core/vasio/VAsioConnection.cpp
SilKit/source/services/logging/Logger.cpp
SilKit/source/util/StringHelpers.cpp
SilKit/source/util/StringHelpers.hpp
docs/configuration/logging-configuration.rst

Ensure that filenames are (more) unique, just in case multiple log files are opened in quick succession.
In the future we might want to provide some templating for the user to choose the file name.

SILKIT-1612 log: add participant name to file names

---

docs/CHANGELOG.rst

Adds a date to the changelog entry for 4.0.53 and fixes some minor issues in the changelog.

docs: add date to 4.0.53 and fix minor issues in changelog

---

README.rst
docs/overview/overview.rst

Harmonizes the 'related projects' section in the documentation overview and readme.
Issue: SILKIT-1585

docs: harmonize readme and overview

---

SilKit/IntegrationTests/ITest_MessageAggregation.cpp
SilKit/source/core/participant/Participant_impl.hpp
SilKit/source/core/vasio/VAsioRegistry.cpp
SilKit/source/services/metrics/MetricsReceiver.cpp
SilKit/source/services/metrics/MetricsReceiver.hpp
SilKit/source/services/orchestration/TimeSyncService.hpp

Remove a few unused variables that caused warnings with some compilers.

maintenance: remove unused capture, member, and argument

---

SilKit/IntegrationTests/ITest_Internals_DataPubSub.cpp
SilKit/IntegrationTests/ITest_Internals_DataPubSub.hpp
SilKit/IntegrationTests/ITest_Internals_Rpc.cpp
SilKit/IntegrationTests/ITest_Internals_Rpc.hpp
SilKit/source/config/ParticipantConfiguration.cpp
SilKit/source/config/ParticipantConfiguration.hpp
SilKit/source/config/ParticipantConfiguration.schema.json
SilKit/source/config/ParticipantConfigurationFromXImpl.cpp
SilKit/source/config/ParticipantConfiguration_Full.json
SilKit/source/config/ParticipantConfiguration_Full.yaml
SilKit/source/config/SilKitYamlHelper.hpp
SilKit/source/config/YamlConversion.cpp
SilKit/source/config/YamlConversion.hpp
SilKit/source/config/YamlSchema.cpp
SilKit/source/core/participant/Participant.hpp
SilKit/source/core/participant/Participant_impl.hpp
SilKit/source/services/logging/SilKitFmtFormatters.hpp
docs/CHANGELOG.rst
docs/configuration/services-configuration.rst

This PR implements an extension to the participant configuration that allows to override the labels of `DataPublisher`, `DataSubscriber`, `RpcClient`, and `RpcServer` controllers in the participant configuration.
The format (all other controllers analogous) is like this:
```yaml
RpcClients:
- Name: MyRpcController
Labels:
- Key: SomeKey
Value: SomeValue
Kind: Mandatory
- Key: AnotherKey
Value: AnotherValue
Kind: Optional
```
The labels **completely replace** what is specified in the code.
This is just a proposal to play around with, it is not neccessarily the final form.
JIRA Issue SILKIT-1636

config: allow overriding rpc and pub/sub labels

---

CMakeLists.txt
SilKit/cmake/SilKitBuildTools.cmake

Splitting archives is not supported. Only ELF shared objects in Debug builds

cmake: don`t split debug symbols off of static libs

---

SilKit/cmake/SilKitVersion.cmake
docs/CHANGELOG.rst

Bump SilKitVersion.cmake + Changelog to 4.0.55

bump version to 4.0.55

---

SilKit/include/silkit/capi/Lin.h
docs/CHANGELOG.rst

When linking two separately compiled object files, both using the C-API, the linker informed me about a multiply defined symbol. This turned out to be the `const` global `SilKit_LinDataLengthUnknown`.
I did grep through the C headers and haven't found another one of those.
Neither the `.dll` nor the `.so` export this symbol so no trouble there.
Issue: SILKIT-1654

c-api: turn const global into define

---

docs/api/capi/capi-lin.rst

Fixes warning caused by invalid doxygen reference. Fallout from the lin-header fix (`doxygenvariable` does not reference `#define`s).

docs: fix invalid reference causing warning

---

README.rst
docs/for-developers/developers.rst

Add the platform support info for SIL Kit

Platform support

---

README.rst

Actually show the ARM64 badge for Ubuntu

README: show Ubuntu ARM64 badge

---

SilKit/include/silkit/capi/Types.h
SilKit/include/silkit/detail/impl/ThrowOnError.hpp
SilKit/source/capi/CMakeLists.txt
SilKit/source/capi/CapiImpl.hpp
SilKit/source/capi/Test_CapiExceptions.cpp
SilKit/source/capi/Test_CapiSilKit.cpp
SilKit/source/config/CMakeLists.txt
SilKit/source/config/TestParticipantConfigs/ParticipantConfiguration_TestCapi.yaml
docs/CHANGELOG.rst

SIL Kit specific exceptions (e.g. `SilKit::ConfigurationError`) are not transported to the C++ side through the hourglass. There, only the exception `Silkit::SilkitError` is thrown (_ThrowOnError.hpp_)
In this PR:
- `SilKit_ReturnCodeXYZ` for all specific exceptions
- The `CAPI_CATCH_EXCEPTIONS` macro catches the specific exception and returns the corresponding `SilKit_ReturnCode_XYZ`
- In _ThrowOnError.hpp_, the return code leads to the specific exception again
- Tests for `CAPI_CATCH_EXCEPTIONS` and `ThrowOnError()` in _Test_CApiExceptions.cpp_
- Fix _Test_CapiSilKit_ which was using outdated arguments in `CreateParticipant`. Also, the silkit_function_mapping test was misleading, as it was actually only testing for bad / invalid parameters with wrong expectations.

SILKIT-1650: Forward specific SIL Kit exceptions

---

CMakeLists.txt
SilKit/IntegrationTests/ITest_CompatibilityWithWindowsHeaders.cpp
SilKit/include/silkit/detail/impl/ThrowOnError.hpp
SilKit/include/silkit/participant/exception.hpp
SilKit/source/CMakeLists.txt
SilKit/source/MakeVersionMacros.cmake.in
SilKit/source/capi/CapiUtils.cpp
SilKit/source/config/ParticipantConfiguration.hpp
SilKit/source/config/ParticipantConfigurationFromXImpl.cpp
SilKit/source/config/SilKitYamlHelper.hpp
SilKit/source/config/YamlValidator.cpp
SilKit/source/core/vasio/VAsioDatatypes.hpp
SilKit/source/core/vasio/VAsioProtocolVersion.hpp
SilKit/source/core/vasio/VAsioSerdes_Protocol30.cpp
SilKit/source/extensions/SilKitExtensionApi/SilKitExtensionABI.h
SilKit/source/extensions/SilKitExtensionApi/SilKitExtensionBase.hpp
SilKit/source/extensions/SilKitExtensionImpl/DllCache.hpp
SilKit/source/extensions/SilKitExtensionImpl/SilKitExtensionLoader.hpp
SilKit/source/extensions/SilKitExtensions.cpp
SilKit/source/extensions/SilKitExtensions.hpp
SilKit/source/tracing/CMakeLists.txt
SilKit/source/tracing/IReplay.hpp
SilKit/source/tracing/ReplayScheduler.cpp
docs/troubleshooting/interoperability.rst

- Completed C strings in SilKit\source\capi\CapiUtils.cpp
- More clear exception message formatting
- Replaced `SILKIT` with `SIL Kit`

dev: String definitions for SIL Kit error return codes

---

Demos/Benchmark/BenchmarkDemo.cpp

The Benchmark Demo has been extended by can and ethernet (so far only pubsub available). The service type can be determined via a command line argument (cf. silkit-1579).
Additional minor change: The simulation step size can be adapted via the command line.

demos: extend benchmark demo by can and ethernet

---

SilKit/include/silkit/capi/Can.h
SilKit/include/silkit/capi/Orchestration.h

As reported by a user of the C-API, the pointer typedefs don't match the actual declarations.

capi: fix function pointer arguments in declaration

---

SilKit/IntegrationTests/ITest_SystemMonitor.cpp
SilKit/source/core/mock/nullconnection/NullConnectionParticipant.cpp
SilKit/source/core/participant/Participant_impl.hpp
SilKit/source/core/vasio/VAsioConnection.cpp
SilKit/source/core/vasio/VAsioConnection.hpp
SilKit/source/services/orchestration/SystemMonitor.cpp
SilKit/source/services/orchestration/SystemStateTracker.cpp
SilKit/source/services/orchestration/SystemStateTracker.hpp
SilKit/source/services/rpc/RpcTestUtilities.hpp

The SystemMonitor does not know about participants which are "older" than the current participants since he misses the Announcement and AnnouncementReplies
Get the list of all connected peers/particpants, that have joined the simulation before, from the VAsioConnection. This ensures that the SystemMonitor also knows about other Participants whose Announcement/AnnouncementReply we missed!
Issues: SILKIT-1660

SILKIT-1660: SystemMonitor: query older participants from VAsio

---

Demos/communication/include/ApplicationBase.hpp
Demos/communication/include/SignalHandler.hpp
SilKit/source/util/SignalHandler.cpp
SilKit/source/util/SignalHandler.hpp
Utilities/SilKitSystemController/SystemController.cpp

The worker thread of the static signal handler (holding user callbacks) is potentially destruced after the participant. TSAN runs showed use-after-free problems in the `sil-kit-system-controller` when using CTRL-C on it in a running simulation (EthernetDemo). 
Here a explicit function `SilKit::Util::ShutdownSignalHandler` is introduced that destroys the `gSignalMonitor`. Using this at the end of the `sil-kit-system-controller` resolves the TSAN issue. Same is applied to the `ApplicationBase` of the communication demos that also uses the signal handler.

dev: Allow to explicitly reset the static signal handler

---

Demos/communication/Lin/LinMasterDemo.cpp
Demos/communication/Lin/LinMasterDynamicDemo.cpp

Fixes (corretly) dropped frames caused by using too tight of a schedule in the LIN demo.

demos: fix schedule used for sending lin frames

---

SilKit/IntegrationTests/CMakeLists.txt
SilKit/IntegrationTests/ITest_LabelsMatching.cpp
SilKit/source/services/rpc/RpcServer.cpp
SilKit/source/services/rpc/RpcServer.hpp

In a specific label setup, an additional `RPCServerInternal` is incorrectly created. This means that with one client call you suddenly get two calls to the RPC server's handler.
In the fix here, a map for `internalRpcServers` is used for  the RPCServer and thus multiple creation of `RPCServerInternals` for the same ClientUUID is prevented.

SILKIT-1691: Prevent creation of multiple RPCServerInternal for same ClientUUID

---

docs/troubleshooting/performance.rst

Fixes the build error that occured in the internal pipeline.

docs: fix warning in section heading

---

README.rst

we should link to the public product page of SIL Kit

Add vector sil-kit page as badge

---

.github/workflows/build-win.yml
Demos/api/Orchestration/SimStepAsync.cpp
docs/CHANGELOG.rst

Fixes the `SilKitDemoSimStepAsync`. The predicate lambda captured the 'guard' variable by value instead of by reference, leading to infinite waiting.

Dev fix async demo

---

.github/workflows/build-win.yml
SilKit/ci/docker/docs_requirements.txt
SilKit/include/silkit/capi/Lin.h
SilKit/include/silkit/capi/NetworkSimulator.h
docs/CMakeLists.txt
docs/conf.py

- Add the `myst-parser` as a docs requirement (Markdown).
- Let CMake find the python interpreter used for building the HTML documentation. This should enable using virtual environments in the documentation build.
- Auto-upgrade the `Doxyfile` to support more modern `doxygen` versions
- Fix some documentation comments that are not supported by modern `doxygen` versions

docs: add myst-parser and let cmake find python

---

SilKit/source/services/orchestration/Test_TimeSyncService.cpp
SilKit/source/services/orchestration/TimeSyncService.cpp

This change fixes an issue with hopping onto running time-synchronized simulations with a participant with an autonomous lifecycle.
The bug can cause a participant to release it's sim step 'early' and cause other participants to execute their next simulation step too early.
**TODO**:

hop-on: send current sim. task instead of next inside of sim. step

---

docs/CHANGELOG.rst

Ubuntu 18.04 is EOL, and we should provide up-to-date Ubuntu binary packages.

Heads-up: we are sunsetting distribution of Ubuntu 18.04 binary packages

---

SilKit/IntegrationTests/Hourglass/MockCapi.cpp
SilKit/IntegrationTests/Hourglass/MockCapi.hpp
SilKit/IntegrationTests/Hourglass/Test_HourglassOrchestration.cpp
SilKit/IntegrationTests/ITest_AsyncSimTask.cpp
SilKit/include/silkit/capi/Orchestration.h
SilKit/include/silkit/detail/impl/experimental/services/orchestration/TimeSyncServiceExtensions.ipp
SilKit/include/silkit/detail/impl/services/orchestration/TimeSyncService.hpp
SilKit/include/silkit/experimental/services/orchestration/TimeSyncDatatypesExtensions.hpp
SilKit/include/silkit/experimental/services/orchestration/TimeSyncServiceExtensions.hpp
SilKit/source/capi/CapiOrchestration.cpp
SilKit/source/capi/Test_CapiSymbols.cpp
SilKit/source/experimental/CMakeLists.txt
SilKit/source/experimental/services/orchestration/TimeSyncServiceExtensionsImpl.cpp
SilKit/source/experimental/services/orchestration/TimeSyncServiceExtensionsImpl.hpp
SilKit/source/services/orchestration/TimeSyncService.cpp
SilKit/source/services/orchestration/TimeSyncService.hpp
docs/CHANGELOG.rst

This is the first draft of an experimental API extension. Function and file names might still change, this PR is meant as a preview of the new functionality. This PR also lacks integration tests.

time-sync: add experimental other-simulation-steps-completed api

---

docs/for-developers/developers.rst

State that we officialy support Ubuntu 24.04 packages in the platform docs.

docs: update platform to include Ubuntu 24.04

---

SilKit/include/silkit/detail/impl/services/lin/LinController.hpp
SilKit/include/silkit/services/lin/ILinController.hpp
SilKit/include/silkit/services/orchestration/ISystemMonitor.hpp

Fix missing virtual destructor and harmful `noexcept` from public API.

major bump: fix some shortcomings of public interfaces

---

SilKit/IntegrationTests/CMakeLists.txt
SilKit/IntegrationTests/ITest_PubHistory.cpp
SilKit/source/config/ParticipantConfiguration.hpp
SilKit/source/config/ParticipantConfiguration.schema.json
SilKit/source/config/ParticipantConfiguration_Full.json
SilKit/source/config/ParticipantConfiguration_Full.yaml
SilKit/source/config/YamlReader.cpp
SilKit/source/config/YamlValidator.cpp
SilKit/source/config/YamlWriter.cpp
SilKit/source/core/participant/Participant_impl.hpp
docs/CHANGELOG.rst

Makes it possible to override the publisher history length in the participant configuration. Analogous to the override of the topic, or the labels.
JIRA: SILKIT-1777
- [x Squash and merge &rarr; proper PR title

config: enable configuration override for publisher history length

---

SilKit/cmake/SilKitVersion.cmake

Finally implement the new semantic versioning. 
I'm fed up with users asking "is there anything new since version 4.0.33" 🤣
TODO for 5.0:
- build RelWithDebInfo as default for distributions
- Changelog in MD format, and move old Changelog entries into separate files?
- LTO on some platform/compilers? see #227

cmake: bump version to 5.0.0 🚀

---

SilKit/cmake/SilKitBuildSettings.cmake
SilKit/cmake/qnx-cross-base-toolchain.cmake

GCC 8 based compilers need to explicitly link against libstdc++fs or libc++fs to work

Fix GCC 8 and QNX710 for std::filesystem

---

.github/actions/build-cmake-preset/action.yml
SilKit/IntegrationTests/ITest_Internals_ParticipantModes.cpp

this integration test hangs irregularly on some runners

itest: add timeout for participant modes test

---

SilKit/source/services/logging/Logger.cpp

Logging messages without `kv`, that is a single `JsonString` was broken. The user-messages was not formatted as JSON.

log: fix json logging without keyvals

---

CMakePresets.json
SilKit/cmake/toolchain-qnx-aarch64.cmake

1. Fixes the wrong toolset selection for QNX aarch64
2. Sets the correct default installation path for the QNX CMake presets
1. The QNX build for aarch64 was failing due to a wrong target toolset selection. When the "_cxx" suffix is appended to the originally selected "gcc_ntoaarch64le_gpp", it results in an unknown toolset target "gcc_ntoaarch64le_gpp_cxx". By removing the "_gpp" suffix, it results in a correct toolset target "gcc_ntoaarch64le_cxx".
2. The QNX presets did not have an `installDir` set, so the installation path was defaulting to `/usr/local`. Now the QNX presets inherit the `mixin-dirs` and have the same `installDir` as the other presets.
Are there any other files I missed with my fixes?

Fix CMake configuration for QNX targets
